export const PRIVACY_OPTIONS = {
    ALL: 'ALL',
    FRIENDS: 'FRIENDS',
    PRIVATE: 'PRIVATE'
}

export const DEFAULT_FEED_INCREMENTS = 10


export const NOTIFICATION_TYPES = {
    FRIEND_REQUEST: 'FRIEND_REQUEST',
    GROUP_INVITE: 'GROUP_INVITE',
}
